name: Iphonagraphy
favicon: null
layout_spectrum: 0.51295
typography_spectrum: 0.4032258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfafb'
    - '#d4d1d2'
    - '#aba8aa'
    - '#453842'
    - '#6f5d68'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.4399936
purpose: []
