name: Moments
favicon: null
layout_spectrum: 0.31754
typography_spectrum: 0.4032258
title: Moments of iPhonagraphy and other cameras ;-)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfafb'
    - '#d4d1d2'
    - '#aba8aa'
    - '#453842'
    - '#6f5d68'
  brandStrength: 0
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.4399936
purpose: []
